### ISSUE TITLE
A question on plot.py

### ISSUE THREAD

**Issue by srzer** [YangRui2015/RiC#3]
Why should the pref_list be reversed?
```
if 'helpful' in path and 'humor' in path:
        if reverse:
            obtained_scores = obtained_scores[:, ::-1]
        if len(pref_lis):
            pref_lis = [1 - x for x in pref_lis]
```

**Comment by YangRui2015** [comment]
Thank you for your question. The is because my previous experiments stored the results in the sequence of 'helpful' and 'humor' (score1, score2 as below), but it is preferred to rearrange the order to 'humor' followed by 'helpful' so that the first two subfigures share the same y-label. Therefore, I reversed the scores and their corresponding preferences.

`obtained_scores.append([np.mean(data['obtained_score1']), np.mean(data['obtained_score2'])])`

You can modify this code to suit your case and I will make this code cleaner.

**Comment by srzer** [comment]
Thx, I understand
