### ISSUE TITLE
some error when conducting ppo

### ISSUE THREAD

**Issue by andyclsr** [YangRui2015/RiC#8]
sorry for confusing the concepts !  it may only need to be finetuned on one dataset.

_Hi, I have a question about the sft model before conducting PPO. Did you conduct sft on different datasets sequentially? Or merge the datasets and conduct sft once ? It seems like there is no detail about it in the paper._

**Comment by andyclsr** [comment]
Hi, I encountered an error "next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) RuntimeError: probability tensor contains either `inf`, `nan` or element < 0" seems like when calling `response_tensors = ppo_trainer.generate(query_tensors, return_prompt=False, **generation_kwargs) ` in the experiment of doing ppo with assistant task and with single reward model "helpful". And ppo in assistant task with reward model "harmless" seems to be fine. 
Did you met this problem? I think it may be related to 8-bit quantification

**Comment by YangRui2015** [comment]
Hi. Regarding your first question, SFT is conducted on a single dataset. For HH-RLHF, it utilizes a combination of harmless and helpful data. On the other hand, the summary task originally is a single dataset.

As for the second question, could you first check the versions of the transformers, peft, accelerate, bitsandbytes, and trl libraries? In my initial experiments, I encountered similar issues, but I haven't experienced them with my current code on GitHub. It seems the issue was resolved with a package update.

**Comment by andyclsr** [comment]
Thanks for the explanations ! I solved the problem by using flash_attn2 and updating the repos. Thanks again for your kind response.

**Comment by YangRui2015** [comment]
great!
